version: '3.3'

services:
  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/flaskmovie
    networks:
      - network1
      - network2
    ports:
      - 5000:5000
    restart: always

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flaskmovie
    image: postgres:14-alpine
    networks:
      - network1
    ports:
      - 5032:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  interprete:
    image: alpine
    stdin_open: true
    tty: true
    networks:
      - network2

networks:
  network1:
  network2:

volumes:
  pgdata:
    external: true
   
