version: '3.3'

services:
  api:
    build: .
    depends_on:
      - db
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:postgres@db/flaskmovie
    networks:
      - default
    ports:
      - 8000:5000
    restart: always

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flaskmovie
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
