version: '3.3'

services:
  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/flaskmovie
    networks:
      - default
    ports:
      - 5000:5000
    restart: always

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flaskmovie
    image: postgres:13-alpine
    networks:
      - default
    ports:
      - 5032:5432
    restart: always
